import React from 'react'

const TermsOfService = () => {
  return (
    <>
      <div className='text-center my-6 prose mx-auto px-4 lg:px-0'>
        <p className='uppercase text-sm'>Legal terms of service</p>
        <h1 className='font-serif text-5xl font-bold'>Terms of Service</h1>
      </div>
      <div className='my-16 prose prose-indigo mx-auto px-6 lg:px-0'>
        <div className='space-y-2 mb-6'>
          <h2 className='font-bold text-xl'>Introduction</h2>
          <p className='text-stone-500 text-base'>
            By using our Tailor & Company clothing manufacturing services, you
            agree to receive communications from us, including but not limited
            to emails, notifications, and other messages. You can opt out of
            receiving certain communications by updating your preferences in
            your account settings.
          </p>
        </div>

        <div className='space-y-2 mb-6'>
          <h2 className='font-bold text-xl'>Communications:</h2>
          <ul className='text-stone-500 text-base'>
            <li>
              By using our Tailor & Company clothing manufacturing services, you
              agree to receive communications from us, including but not limited
              to emails, notifications, and other messages. You can opt out of
              receiving certain communications by updating your preferences in
              your account settings.
            </li>
          </ul>
        </div>

        <div className='space-y-2 mb-6'>
          <h2 className='font-bold text-xl'>Purchases:</h2>
          <p className='text-stone-500 text-base'>
            All purchases of our Tailor & Company clothing manufacturing
            services are subject to our refund policy. Please see the{' '}
            <strong>Refunds</strong> section below for more information.
          </p>
        </div>

        <div className='space-y-2 mb-6'>
          <h2 className='font-bold text-xl'>Features:</h2>
          <p className='text-stone-500 text-base'>
            Our Tailor & Company clothing manufacturing services are constantly
            evolving and improving. We reserve the right to add, remove, or
            modify features at any time without notice.
          </p>
        </div>

        <div className='space-y-2 mb-6'>
          <h2 className='font-bold text-xl'>Free Usage:</h2>
          <p className='text-stone-500 text-base'>
            We offer a free trial period for our Tailor & Company clothing
            manufacturing services. The length of the free trial and the
            features included will be specified at the time of sign-up. After
            the free trial, you will be required to purchase a subscription in
            order to continue using our clothing manufacturing services.
          </p>
        </div>

        <div className='space-y-2 mb-6'>
          <h2 className='font-bold text-xl'>Refunds:</h2>
          <p className='text-stone-500 text-base'>
            We offer a no-questions-asked refund policy for all purchases within
            7 days of the original purchase date. However, if you have used our
            Tailor & Company clothing manufacturing services for more than 20%
            of the capacity, we will not issue a refund. To request a refund,
            please contact us at hey@tailorandcompany.com.
          </p>
        </div>

        <div className='space-y-2 mb-6'>
          <h2 className='font-bold text-xl'>
            Prohibited Use for Illegal Means:
          </h2>
          <p className='text-stone-500 text-base'>
            Our Tailor & Company clothing manufacturing services may only be
            used for lawful purposes. You agree not to use our clothing
            manufacturing services for any illegal or unauthorized purpose,
            including but not limited to committing fraud or engaging in illegal
            activities.
          </p>
        </div>

        <div className='space-y-2 mb-6'>
          <h2 className='font-bold text-xl'>Copyright Policy:</h2>
          <p className='text-stone-500 text-base'>
            You retain the rights to any content that you generate using our
            Tailor & Company clothing manufacturing services. You may use,
            reproduce, distribute, or otherwise exploit the content generated by
            our clothing manufacturing services for any lawful purpose, subject
            to our terms and conditions. Any unauthorized use of our clothing
            manufacturing services or its content may violate copyright laws,
            trademark laws, and other applicable laws.
          </p>
        </div>

        <div className='space-y-2 mb-6'>
          <h2 className='font-bold text-xl'>Contact Us</h2>
          <p className='text-stone-500 text-base'>
            If you have any questions or concerns about our policies or the way
            we handle your personal information, please contact us at
            hello@tailorandcompany.com.
          </p>
        </div>
      </div>
    </>
  )
}

export default TermsOfService
